apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: myapp-analysis
spec:
  args:
  - name: service-name

  metrics:

  # =========================
  # ✅ APP SLO (Availability)
  # =========================
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result >= 0.99
    failureCondition: result < 0.95
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          scalar(
            sum(rate(http_requests_total{app="{{args.service-name}}",status=~"2.."}[1m]))
          )
          /
          scalar(
            sum(rate(http_requests_total{app="{{args.service-name}}"}[1m]))
          )

  # =========================
  # ✅ LATENCY (App)
  # =========================
  - name: latency-p95
    interval: 30s
    count: 3
    successCondition: result < 0.5
    failureCondition: result >= 0.8
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile(
            0.95,
            sum(rate(http_request_duration_seconds_bucket{app="{{args.service-name}}"}[1m])) by (le)
          )

  # =========================
  # ✅ K6 ERROR RATE
  # =========================
  - name: k6-error-rate
    interval: 30s
    count: 3
    successCondition: result < 0.05
    failureCondition: result >= 0.10
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          scalar(avg(k6_error_rate))

  # =========================
  # ✅ K6 LATENCY
  # =========================
  - name: k6-latency-p95
    interval: 30s
    count: 3
    successCondition: result < 500
    failureCondition: result >= 800
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          scalar(avg(k6_latency_p95))