apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - analysis-template.yaml
  - analysis-template-k6.yaml
  - analysis-template-chaos.yaml
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:3c538b2c02192eb8e7d6a1b20df77eaa911e2d23a22ef71d047f9209685b0335
patches:
  - target:
      kind: Rollout
      name: myapp
    path: env.yaml
  - target:
      kind: Rollout
      name: myapp
    path: replicas.yaml
  - target:
      kind: Deployment
      name: myapp
    path: delete-deployment.yaml
