apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - analysis-template.yaml
  - analysis-template-chaos.yaml
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:7dc4e721289d7ca37f3ca7b40af986ec13801c5049e98b5d4bb05fe8c69bd3c0
patches:
  - target:
      kind: Rollout
      name: myapp
    path: env.yaml
  - target:
      kind: Rollout
      name: myapp
    path: replicas.yaml
  - target:
      kind: Deployment
      name: myapp
    path: delete-deployment.yaml
