apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pt
resources:
  - ../../base-deployment

images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    newTag: sha256-pt123

patches:
  - path: replicas.yaml
  - path: env.yaml