apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pt
resources:
  - ../../base
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:23970c84d8ac3058d898f13a03272b07e9f185d7f880eba62ca4ce8b9c055d54
patches:
  - path: replicas.yaml
  - path: env.yaml
  - path: delete-rollout.yaml
