apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pt
resources:
  - ../../base
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:2f6b8cfbcac0d07830b027750b8dc3b95197c29a7da37b8688f1558ab0716c9a
patches:
  - path: replicas.yaml
  - path: env.yaml
  - path: delete-rollout.yaml
