apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-smoke-test
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: smoke-test
        image: curlimages/curl:8.5.0
        command:
          - sh
          - -c
          - |
            echo "Running smoke test..."
            curl -sf http://myapp.dev.svc.cluster.local/health
