apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-smoke-test
  namespace: dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: smoke-test
        image: curlimages/curl:8.4.0
        command:
          - sh
          - -c
          - |
            echo "Running smoke tests..."
            curl -f http://myapp.dev.svc.cluster.local/health
