apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-smoke-test
  namespace: dev
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: smoke-test
        image: curlimages/curl:8.4.0
        command:
          - sh
          - -c
          - |
            echo "Waiting for service DNS..."
            for i in $(seq 1 30); do
              nslookup myapp-service.dev.svc.cluster.local && break
              echo "DNS not ready yet..."
              sleep 5
            done

            echo "Waiting for app health..."
            for i in $(seq 1 30); do
              curl -f http://myapp-service.dev.svc.cluster.local:9000/health && exit 0
              echo "App not ready yet..."
              sleep 5
            done

            echo "Smoke test failed"
            exit 1
