apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../base
  - analysis-template.yaml
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:0df781eef23ae11636b4d768ee30a18f6cec7eebee18d2cec11ecfabdfb16cba
patches:
  - path: replicas.yaml
  - path: env.yaml
  - path: delete-rollout.yaml
