apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa
resources:
  - ../../base
  - analysis-template.yaml
images:
  - name: myapp
    newName: sha256:20d406e513ab3425b3fba9417b4d1665e51ce9b4cdf43dc3ffa8aa2c175c4d35
    digest: sha256:20d406e513ab3425b3fba9417b4d1665e51ce9b4cdf43dc3ffa8aa2c175c4d35
patches:
  - path: replicas.yaml
  - path: env.yaml
  - path: delete-rollout.yaml
