apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: myapp-canary-analysis
spec:
  metrics:

  # -----------------------------
  # Application Success Rate
  # -----------------------------
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result >= 0.99
    failureCondition: result < 0.95
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{app="myapp",status=~"2.."}[1m]))
          /
          sum(rate(http_requests_total{app="myapp"}[1m]))
