apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - analysis-template.yaml
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:977691d9656d0c707eeeb40540b3567fde16393aa293cf2d8ea81c88c1bc4a8a
# Environment-specific tuning
patches:
  - path: replicas.yaml
  - path: env.yaml
  - path: delete-rollout.yaml
