apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - analysis-template.yaml
images:
  - name: myapp
    newName: 281762848319.dkr.ecr.us-east-1.amazonaws.com/myapp
    digest: sha256:3c538b2c02192eb8e7d6a1b20df77eaa911e2d23a22ef71d047f9209685b0335
# Environment-specific tuning
patches:
  - path: replicas.yaml
  - path: env.yaml
  - path: delete-rollout.yaml
